#!/bin/sh

xrandr --output HDMI-A-0 --mode 2560x1440 --rate 144 --output eDP-1 --off &
xrdb -load $XDG_CONFIG_HOME/X11/darkxres &
setxkbmap us,ru -option grp:caps_toggle -print | xkbcomp - $DISPLAY &
xset r rate 240 40
picom -b
feh --bg-scale --no-fehbg $XDG_CONFIG_HOME/wallpapers/wall1.jpg
exec dbus-run-session $WM
