
[font]
size = 12

[font.normal]
#family = "DaddyTimeMono"
family = "Annotation Mono"
style = "Regular"

[font.offset]
x = 0
y = 3

[general]
import = ["themes/atheme.toml"]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
