#!/bin/sh

down() {
	pamixer -d 2
	volume=$(pamixer --get-volume)
	[$volume -gt 0 ] && volume=`expr $volume`  
}

up() {
	pamixer -i 2
	volume=$(pamixer --get-volume)
	[ $volume -lt 1000 ] && volume=`expr $volume`  
}

mute() {
    pamixer -t
}

case "$1" in
    up) up;;
    down) down;;
    mute) mute;;
esac
