theme = "onedark"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
nbsp = "⍽"
tab = "→"
space = "·"

[keys.insert]
k = { j = "normal_mode" }

[keys.normal]
G = "goto_file_end"
X = "extend_line_above"
Z = { Z = ":write-quit" }

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1