"  path to .config 
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')
set viewdir=$XDG_DATA_HOME/vim/view | call mkdir(&viewdir, 'p')

set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir,   'p')

set viminfofile=$XDG_CACHE_HOME/vim/viminfo
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"



" enter the current millenuim
set nocompatible
 
set ts=4
set autoindent
set shiftwidth=4
set nu relativenumber
set cursorline
set cursorlineopt=screenline
set backspace=indent,eol,start
set wildmenu
syntax on
colorscheme myscheme
let g:highlightedyank_highlight_duration = 150
let g:snipMate = {'snippet_version': 1}

" Set IBeam shape in insert mode, underline shape 
" in replace mode and block shape in normal mode. 
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"

" C-V<F9> to copy to clipboard
function Func2X11()
  :call system('xclip -selection c', @r)
endfunction
vnoremap <F9> "ry:call Func2X11()<cr>

" Copy from clipboard/selection without autoident
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"

inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction

set clipboard+=unnamedplus

" Move cursor by display lines when wrapping
inoremap <Down> <C-o>gj
inoremap <Up> <C-o>gk

" add an empty line
nnoremap <silent> [<space> :pu! _<cr>:']+1<cr>
nnoremap <silent> ]<space> :pu _<cr>:'[-1<cr>

let mapleader = "\<Space>"
nnoremap <Leader>w <C-w>
nnoremap <Leader>t :w<CR>
nnoremap Y y$
inoremap jh <Esc>
