preload = ~/.config/wallpapers/wall1.jpg
preload = ~/.config/wallpapers/wall2.jpg
preload = ~/wlds/imgs/930675.jpg
preload = ~/wlds/imgs/1327844.png
wallpaper = eDP-1,~/.config/wallpapers/wall2.jpg
wallpaper = HDMI-A-1,~/wlds/imgs/1327844.png
splash = false
